server.port=8080
spring.application.name=app-06-hr-management

# Data source configurations
spring.datasource.url=jdbc:h2:mem:hrdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JPA & Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Thymeleaf cache disable for development ease
spring.thymeleaf.cache=false

# Logging properties
logging.level.org.springframework.security=INFO
logging.level.com.hr=DEBUG
