server.port=8082
spring.datasource.url=jdbc:h2:mem:warehousedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Planted Vulnerability: Actuator exposure without restrictions
management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=ALWAYS
management.endpoint.health.show-details=always
management.endpoint.heapdump.enabled=true

logging.level.org.springframework.security=DEBUG
