server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:telecomdb;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.kafka.enabled=${APP_KAFKA_ENABLED:false}
app.kafka.audit-topic=${APP_KAFKA_AUDIT_TOPIC:telecom-billing-audit}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:telecom-audit-consumers}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.telecom.billing.events
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
app.elasticsearch.url=${APP_ELASTICSEARCH_URL:http://localhost:9200}
app.elasticsearch.enabled=${APP_ELASTICSEARCH_ENABLED:false}
logging.level.org.springframework.security=INFO
